# Generated by Django 2.2 on 2019-06-08 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionalFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionalfunction',
            name='ALR_aumount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O valor de ALR deve ser maior ou igual a 0')], verbose_name='Parâmetro 1 (ALR)'),
        ),
        migrations.AlterField(
            model_name='transactionalfunction',
            name='DER_aumount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor de DER deve ser maior ou igual a 1')], verbose_name='Parâmetro 2 (DER)'),
        ),
        migrations.AlterField(
            model_name='transactionalfunction',
            name='name',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, message='O nome deve ter pelo menos 3 caracteres')], verbose_name='Nome'),
        ),
    ]
